# Generated by Django 5.0.3 on 2024-04-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
